# Generated by Django 5.1.7 on 2025-12-22 12:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ticket_options_ticket_purchase_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_last_four',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Последние 4 цифры карты'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Кредитная карта'), ('debit_card', 'Дебетовая карта'), ('paypal', 'PayPal'), ('bank_transfer', 'Банковский перевод')], default='credit_card', max_length=50, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='qr_code_data',
            field=models.TextField(blank=True, null=True, verbose_name='Данные QR кода'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Номер билета'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма возврата'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_set', to='api.event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='Standard Ticket', max_length=100, verbose_name='Название билета'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['reference_number'], name='api_ticket_referen_549fad_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user', 'status'], name='api_ticket_user_id_2c102e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['event', 'status'], name='api_ticket_event_i_3db7df_idx'),
        ),
    ]
